/**
 * @author venksster-dev
 */

VALIDATE_POSITIVE_INDEX = 0;
VALIDATE_NEUTRAL_INDEX = 1;
VALIDATE_FORCE_NEGATIVE_INDEX=2;
VALIDATE_REGEX_INDEX=3;

/* BEGIN - types for PREFERENCE items */
PREFERENCE_SWITCH_COMMENTS_PROFILE = 0;
PREFERENCE_SWITCH_COMMENTS_PHOTOS = 1;
PREFERENCE_SWITCH_NOTIFY_ON_COMMENTS = 2;
PREFERENCE_SWITCH_NOTIFY_ON_REVIEWS = 3;
PREFERENCE_CUSTOM_FIELD_AND_BODY1 = 4;
PREFERENCE_CUSTOM_FIELD_AND_BODY2 = 5;
PREFERENCE_LOCATION = 6;
PREFERENCE_ABOUT_ME = 7;
PREFERENCE_PROFILE_THEME = 8;
PREFERENCE_ARTIST_EMAIL = 9;
PREFERENCE_ARTIST_PROFILENAME = 10;
PREFERENCE_RADIOBARS_LICENSE_TYPE = 11;
PREFERENCE_RADIOBARS_GALLERY_TYPE = 12;

/* END - types for PREFERENCE items */

PREFERENCE_THUMBNAIL_SMALL_SIZE_COUNT = 7;
PREFERENCE_THUMBNAIL_MEDIUM_SIZE_COUNT = 5;
PREFERENCE_THUMBNAIL_LARGE_SIZE_COUNT = 4;

ARTIST_PROFILE_THEME_THUMBNAIL_SIZE_SMALL = 1;
ARTIST_PROFILE_THEME_THUMBNAIL_SIZE_MEDIUM = 2;
ARTIST_PROFILE_THEME_THUMBNAIL_SIZE_LARGE = 3;

/* Theme delimiter and algo type */
ARTIST_PROFILE_THEME_THUMBNAIL_LIST_DELIMITER = ',';
ARTIST_PROFILE_THEME_THUMBNAIL_ALGO_NONE = 0;
ARTIST_PROFILE_THEME_THUMBNAIL_ALGO_RANDOM = 1;
ARTIST_PROFILE_THEME_THUMBNAIL_ALGO_RECENT = 2;
ARTIST_PROFILE_THEME_THUMBNAIL_ALGO_CUSTOM  = 3;

/* Indices for the theme protocol from js to php */
PREFERENCE_THEME_TYPE_INDEX = 0;
PREFERENCE_ALGO_TYPE_INDEX = 1;
PREFERENCE_THUMBNAIL_LIST_INDEX = 2;
PREFERENCE_THUMBNAIL_SIZE_INDEX = 3;
PREFERENCE_THUMBNAIL_COUNT_INDEX = 4;

/* Terms of service */
TOS_ACCEPTED = 1;
TOS_REJECTED = 0;

CUSTOM_TITLE = 0;
CUSTOM_BODY = 1;

SUCCESS_WITH_MESSAGE = 2;
SUCCESS = 0;
ERROR_INVALID_SESSION = -1;
ERROR_VALID_SESSION = -2;
ERROR_BAD_POST_DATA = -3;
ERROR_CGRAPHICS_MIN_SIZE = -4;
ERROR_AUTHENTICATION_FAILED = -5;
ERROR_INVALID_USER = -6;
ERROR_ARTIST_DNAME_UNAVAILABLE = -7;
ERROR_MAX_SHOEBOX_COUNT = -8;

ERROR_UNKNOWN = -9999;

FILTER_NONE = -8;

LIBRARY_JCROP = 0;
LIBRARY_IMGAREASELECT = 1;

//This is the width of the image that has the crop suggestion in each review
REVIEW_IMAGE_WIDTH = 550; 

INTERVAL_RELOAD_SCROLL = 300;

MAX_USER_SHOEBOXES = 5;


TAGS_DELIMITER=',';

MAX_TAG_LENGTH = 35;
MAX_DISCUSSION_TITLE_LENGTH = 200;
MAX_PHOTO_NAME_LENGTH = 90;

/* PHOTO SQUARE SIZES */
SIZE_PHOTO_THUMBNAIL = 65;
SIZE_PHOTO_PREVIEW = 90;
SIZE_PHOTO_SNAPSHOT = 140;
SIZE_PHOTO_SNAPSHOT_LARGE = 185;

/* TOGGLE-SWITCH */
SWITCH_CONTROL_GLOBAL_LIGHTS = 'control_lights';

SWITCH_POSITION_OFF = 0;
SWITCH_POSITION_ON = 1;

/* RADIO-BARS */
RADIOBARS_GALLERY_TYPE=1;
RADIOBARS_LICENSE_TYPE=2;

LIGHTBOX_GALLERY_TYPE_GRID=0;
LIGHTBOX_GALLERY_TYPE_TILE=1;

/* PROFILE THEMES */
OPACITY_OPAQUE = 1;
PROFILE_THEME_MINIMALISTIC_THUMBNAIL_OPACITY = 0.4;

/* constants for invalid characters in input fields */
TAG_UNSUPPORTED_CHARACTERS	=	'\;';

/* message prompts */
INPUT_PROMPT_REVIEW_METRIC = 'click to enter a comment about this metric';
INPUT_PROMPT_REVIEW_GENERAL = 'what do you like or dislike about this photograph?';
UPLOAD_PHOTOS_GLOBAL_TAGS_INPUT_PROMPT = 'click to enter global tags separated by COMMA (,)';
INVALID_TAG_CHARACTERS_MESSAGE = 'Please remove invalid characters ( ;: ) from the tags';
FILTER_BY_TAGS_AND_NAMES_PROMPT = 'filter by tags and names';


/* Upload max photo size */
UPLOAD_MAX_PHOTO_SIZE = 4194304;
//UPLOAD_MAX_PHOTO_SIZE = 100000;

/* KEYCODES */
KEYCODE_ENTER = 13;
KEYCODE_ESCAPE = 27;