<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
*/
$config['base_url']	= "http://127.0.0.1";

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = "";

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of "AUTO" works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']	= "AUTO";

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = "";

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= "english";

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = "UTF-8";

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the "hooks" feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'C';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string "words" that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] 	= 'c';
$config['function_trigger'] 	= 'm';
$config['directory_trigger'] 	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to 
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 4;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/logs/ folder.  Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Sessions class with encryption
| enabled you MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = "";

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'session_cookie_name' = the name you want for the cookie
| 'encrypt_sess_cookie' = TRUE/FALSE (boolean).  Whether to encrypt the cookie
| 'session_expiration'  = the number of SECONDS you want the session to last.
|  by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']		= 'ci_session';
$config['sess_expiration']		= 7200;
$config['sess_encrypt_cookie']	= FALSE;
$config['sess_use_database']	= FALSE;
$config['sess_table_name']		= 'ci_sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update'] 	= 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
|
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not "echo" any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are "local" or "gmt".  This pref tells the system whether to use
| your server's local time as the master "now" reference, or convert it to
| GMT.  See the "date helper" page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;

//require 'require'.EXT;

/*
|--------------------------------------------------------------------------
| Lockdown mode
|--------------------------------------------------------------------------
|
| Log files for module level logging
|
*/
$config['lightbox_login_lockdown'] = false;
$config['lightbox_lockdown'] = false;
$config['lightbox_lockdown_allowed_controllers'] = array('gateway','upload','csession','meta','photoexplore','photo','artist');
//$config['lightbox_lockdown_redirect_controller'] = '/gateway';
$config['lightbox_lockdown_redirect_controller'] = '/error/loggedout';

/*
|--------------------------------------------------------------------------
| CEmail
|--------------------------------------------------------------------------
|
| Log files for module level logging
|
*/
$config['cemail_smtp_host'] = 'ssl://smtp.googlemail.com';
$config['cemail_smtp_port'] = '465';
$config['cemail_smtp_username'] = 'notifications@creya.com';
$config['cemail_smtp_password'] = '758943758064327586243';

/*
|--------------------------------------------------------------------------
| 404 screen logging
|--------------------------------------------------------------------------
|
| Controls the display of debug messages on 404
|
*/
$config['on_error_debug_mode'] = false;

/*
|--------------------------------------------------------------------------
| Module Level Logging - Files
|--------------------------------------------------------------------------
|
| Log files for module level logging
|
*/
require(LIBPATH.'CLogger'.EXT);

$config['logfile_photo'] 				= LOGPATH.'photo.log';
$config['logfile_group'] 				= LOGPATH.'group.log';
$config['logfile_artist'] 				= LOGPATH.'artist.log';

$config['logfile_stats'] 				= LOGPATH.'stats.log';

$config['logfile_util'] 				= LOGPATH.'util.log';
$config['logfile_auth'] 				= LOGPATH.'auth.log';
$config['logfile_dashboard'] 			= LOGPATH.'dashboard.log';

$config['logfile_photoexplore'] 		= LOGPATH.'photoexplore.log';
$config['logfile_groupexplore'] 		= LOGPATH.'groupexplore.log';
$config['logfile_shoeboxexplore'] 		= LOGPATH.'shoeboxexplore.log';
$config['logfile_communityexplore'] 		= LOGPATH.'community.log';
$config['logfile_gdiscussionexplore'] 	= LOGPATH.'photoexplore.log';

$config['logfile_communitypost'] 		= LOGPATH.'photoexplore.log';

$config['logfile_shoebox'] 		= LOGPATH.'shoebox.log';

$config['logfile_community'] 		= LOGPATH.'community.log';

$config['logfile_cranker'] 		= LOGPATH.'cranker.log';

$config['logfile_csession'] 			= LOGPATH.'csession.log';
$config['logfile_gateway'] 			= LOGPATH.'gateway.log';
$config['logfile_cgraphics'] 			= LOGPATH.'cgraphics.log';
$config['logfile_upload'] 			= LOGPATH.'upload.log';

/*
|--------------------------------------------------------------------------
| Module Level Logging - Levels
|--------------------------------------------------------------------------
|
| Log files for module level logging
|
*/

$config['loglevel_global']			= CLogger::$DEBUG;

$config['loglevel_photos'] 			= CLogger::$INFO;
$config['loglevel_groups'] 			= CLogger::$INFO;

$config['loglevel_photo'] 			= CLogger::$DEBUG;
$config['loglevel_group'] 			= CLogger::$INFO;
$config['loglevel_artist'] 			= CLogger::$INFO;

$config['loglevel_stats'] 			= CLogger::$INFO;

$config['loglevel_util']				= CLogger::$DEBUG;
$config['loglevel_auth']				= CLogger::$INFO;
$config['loglevel_dashboard']			= CLogger::$INFO;

$config['loglevel_photoexplore']		= CLogger::$INFO;
$config['loglevel_groupexplore']		= CLogger::$INFO;
$config['loglevel_shoeboxexplore']		= CLogger::$INFO;
$config['loglevel_communityexplore']	= CLogger::$INFO;
$config['loglevel_gdiscussionexplore']	= CLogger::$INFO;

$config['loglevel_communitypost']		= CLogger::$INFO;

$config['loglevel_community']		= CLogger::$INFO;

$config['loglevel_shoebox']		= CLogger::$INFO;

$config['loglevel_csession']			= CLogger::$INFO;
$config['loglevel_cgraphics']			= CLogger::$INFO;
$config['loglevel_upload']			= CLogger::$INFO;
$config['loglevel_gateway']			= CLogger::$INFO;

/*
|--------------------------------------------------------------------------
| CGraphics 
|--------------------------------------------------------------------------
|
| Image Sizes for the CGraphics image stack
|
*/
$config['img_size_zoom']		= 500;
$config['img_size_standard']	= 400;
$config['img_size_snapshot']	= 300;
$config['img_size_preview']		= 200;
$config['img_size_thumbnail']	= 100;

/*
|--------------------------------------------------------------------------
| GENERAL
|--------------------------------------------------------------------------
|
| General parameters for Lightbox
|
*/
$config['num_metrics']		= 3;
$config['top_num_pics']		= 5;
$config['rating_precision']	= 2;

/*
|--------------------------------------------------------------------------
| CGraphics 
|--------------------------------------------------------------------------
|
| Image Sizes for the CGraphics image stack
|
*/
//$config[PHOTO_ZOOM]	= array( 'x' => 1920, 'y' => 1280, 'OPERATION_TYPE'=>RESIZE_ORIENTATION,'path' =>PHOTO_ZOOM_PATH);
$config[PHOTO_STANDARD]	= array('x' => 920, 'y' => 700, 'OPERATION_TYPE'=>RESIZE_ORIENTATION, 'path' =>PHOTO_STANDARD_PATH);
$config[PHOTO_SNAPSHOT_TILE]		= array('x' => 300, 'y' => -1, 'OPERATION_TYPE'=>RESIZE_ORIENTATION, 'path' =>PHOTO_SNAPSHOT_TILE_PATH);
$config[PHOTO_SNAPSHOT]	= array('x' =>140,'y' => 140, 'OPERATION_TYPE'=>RESIZE_FIXED, 'path' =>PHOTO_SNAPSHOT_PATH);
$config[PHOTO_CAPTURE]	= array('x' =>160,'y' => 160, 'OPERATION_TYPE'=>RESIZE_FIXED, 'path' =>PHOTO_CAPTURE_PATH);
$config[PHOTO_PREVIEW]	= array('x' => 90,'y' => 90, 'OPERATION_TYPE'=>RESIZE_FIXED, 'path' =>PHOTO_PREVIEW_PATH);
$config[PHOTO_THUMBNAIL]	= array('x' => 65,'y' => 65, 'OPERATION_TYPE'=>RESIZE_FIXED, 'path' =>PHOTO_THUMBNAIL_PATH);
$config[PHOTO_PANORAMA]	= array('x' => 890,'y' => 350, 'OPERATION_TYPE'=>RESIZE_FIXED, 'path' =>PHOTO_PANORAMA_PATH);

$config[ARTIST_AVATAR_STANDARD]	= array('x' =>170,'y' => 170, 'path' =>ARTIST_AVATAR_STANDARD_PATH);
$config[ARTIST_AVATAR_PREVIEW]	= array('x' => 90,'y' => 90, 'path' =>ARTIST_AVATAR_PREVIEW_PATH);
$config[ARTIST_AVATAR_THUMBNAIL_MEDIUM]	= array('x' => 50,'y' => 50, 'path' =>ARTIST_AVATAR_THUMBNAIL_MEDIUM_PATH);
$config[ARTIST_AVATAR_THUMBNAIL_SMALL]	= array('x' => 40,'y' => 40, 'path' =>ARTIST_AVATAR_THUMBNAIL_SMALL_PATH);
$config[ARTIST_AVATAR_CAPTURE]	=	array('x' => 225,'y' => 225, 'path' =>ARTIST_AVATAR_CAPTURE_PATH);
$config[ARTIST_AVATAR_PROFILE]	=	array('x' => 225,'y' => 225, 'path' =>ARTIST_AVATAR_PROFILE_PATH);

//$config[GROUP_PREVIEW_CAPTURE]	= array('x' =>160,'y' => 160, 'path' =>GROUP_PREVIEW_CAPTURE_PATH);
$config[GROUP_PREVIEW_PANORAMA] = array('x' => 890,'y' => 350, 'OPERATION_TYPE'=>RESIZE_FIXED, 'path' =>GROUP_PREVIEW_PANORAMA_PATH);
$config[GROUP_PREVIEW_SPANORAMA] = array('x' => 390,'y' => 180, 'OPERATION_TYPE'=>RESIZE_FIXED, 'path' =>GROUP_PREVIEW_SPANORAMA_PATH);
$config[GROUP_PREVIEW_THUMBNAIL_MEDIUM] = array('x' => 245,'y' => 200, 'OPERATION_TYPE'=>RESIZE_FIXED, 'path' =>GROUP_PREVIEW_THUMBNAIL_MEDIUM_PATH);

$config[GROUP_DISCUSSION_STANDARD] = array('x' => 620, 'y' => -1, 'OPERATION_TYPE'=>RESIZE_ORIENTATION, 'path' =>GROUP_DISCUSSION_STANDARD_PATH);
$config[GROUP_DISCUSSION_CAPTURE]	= array('x' =>160,'y' => 160, 'OPERATION_TYPE'=>RESIZE_FIXED, 'path' =>GROUP_DISCUSSION_CAPTURE_PATH);

$config[DISCUSSION_STANDARD] = array('x' => 645,'y' => -1, 'OPERATION_TYPE'=>RESIZE_ORIENTATION,'path' =>COMMUNITY_DISC_STANDARD_PATH);
$config[DISCUSSION_CAPTURE]	= array('x' => 160,'y' => 160,  'OPERATION_TYPE'=>RESIZE_FIXED, 'path' =>COMMUNITY_DISC_CAPTURE_PATH);
$config[DISCUSSION_PREVIEW]	= array('x' => 277,'y' => 200,  'OPERATION_TYPE'=>RESIZE_FIXED, 'path' =>COMMUNITY_DISC_PREVIEW_PATH);


//$config['image_library'] = 'imagemagick';
//$config['library_path'] = 'C:/Progra~1/ImageMagick-6.4.9-Q16';
$config['cgraphics_timeout'] = 85;
$config['http_timeout'] = 0;

$config[EXIF_FNUMBER_CODE] = array ( 'dbstring' => 'photo_exif_aperture' , 'matchstring' => EXIF_FNUMBER_STR );
$config[EXIF_FOCALLENGTH_CODE] = array ( 'dbstring' => 'photo_exif_focal' , 'matchstring' => EXIF_FOCALLENGTH_STR );
$config[EXIF_SOFTWARE_CODE] = array ( 'dbstring' => 'photo_exif_sw' , 'matchstring' => EXIF_SOFTWARE_STR );
$config[EXIF_METERINGMODE_CODE] = array ( 'dbstring' => 'photo_exif_mm' , 'matchstring' => EXIF_METERINGMODE_STR );
$config[EXIF_WHITEBALANCE_CODE] = array ( 'dbstring' => 'photo_exif_wb' , 'matchstring' => EXIF_WHITEBALANCE_STR );
$config[EXIF_FLASH_CODE] = array ( 'dbstring' => 'photo_exif_flash' , 'matchstring' => EXIF_FLASH_STR );
$config[EXIF_ISOSPEEDRATINGS_CODE] = array ( 'dbstring' => 'photo_exif_iso' , 'matchstring' => EXIF_ISOSPEEDRATINGS_STR );
$config[EXIF_EXPOSURETIME_CODE] = array ( 'dbstring' => 'photo_exif_shutter' , 'matchstring' => EXIF_EXPOSURETIME_STR );
$config[EXIF_MODEL_CODE] = array ( 'dbstring' => 'photo_exif_camera' , 'matchstring' => EXIF_MODEL_STR );
$config[EXIF_DATETIME_CODE] = array ( 'dbstring' => 'photo_exif_time' , 'matchstring' => EXIF_DATETIME_STR );

$config[NUMERIC_EXPOSURE_VALUES] = array(30,25,20,15,13,10,8,6,5,4,3.2,2.5,2,1.6,1.3,
				1,0.8,0.6,0.5,0.4,0.3,1/4,1/5,1/6,1/8,1/10,1/13,1/15,1/20,1/25,
				1/30,1/40,1/50,1/60,1/80,1/100,1/125,1/160,1/200,1/250,1/320,
				1/400,1/500,1/640,1/800,1/1000,1/1250,1/1600,1/2000,1/2500,1/3200,1/4000);
				
$config[STRING_EXPOSURE_VALUES] = array('30','25','20','15','13','10','8','6','5','4','3"2','2"5','2"','1"6','1"3',
				'1"','0"8','0"6','0"5','0"4','0"3','1/4','1/5','1/6','1/8','1/10','1/13','1/15','1/20','1/25',
				'1/30','1/40','1/50','1/60','1/80','1/100','1/125','1/160','1/200','1/250','1/320',
			'1/400','1/500','1/640','1/800','1/1000','1/1250','1/1600','1/2000','1/2500','1/3200','1/4000');

$config[EXPOSURE_MAP] = array ( NUMERIC_EXPOSURE_VALUES => $config[NUMERIC_EXPOSURE_VALUES],
								STRING_EXPOSURE_VALUES => $config[STRING_EXPOSURE_VALUES] ); 

/*
|--------------------------------------------------------------------------
| CImageUploader 
|--------------------------------------------------------------------------
| 
*/
$config['max_size']	= '20000';
$config['max_width']  = '3500';
$config['max_height']  = '3500';


/*
|--------------------------------------------------------------------------
| CUtil configuration 
|--------------------------------------------------------------------------
| 
*/
//array storing relative date strings
$config['relative_date_mapping'] = array(
					HOUR_DURATION_SECONDS	=> array('hour ago','hours ago'),
					DAY_DURATION_SECONDS	=> array('day ago','days ago'),
					WEEK_DURATION_SECONDS	=> array('week ago','weeks ago') , 
					MONTH_DURATION_SECONDS	=> array('month ago','months ago'),
					MINUTE_DURATION_SECONDS	=> array('minute ago','minutes ago')
				);

/* End of file config.php */
/* Location: ./system/application/config/config.php */
